name: Bug Report
description: Create a bug report
title: "Bug: "
labels: ["bug"]
assignees:
  - timokoessler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A brief description of the bug.
      placeholder: What is the bug about? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      placeholder: How can the bug be reproduced?
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: Provide the error message / stack trace
      placeholder: Paste the error message or stack trace here, if available
    validations:
      required: false
  - type: input
    id: win-version
    attributes:
      label: What version of Windows are you using?
      description: Please enter the entire version number, e.g. Windows 11 26100
      placeholder: Your Windows version
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: What version and edition of the app are you using?
      placeholder: The app version, e.g. 1.0.0 and the edition, e.g. Microsoft Store, Portable or Installer
    validations:
      required: true
