blank_issues_enabled: false
contact_links:
  - name: ⁉️ Questions
    url: https://github.com/timokoessler/2FAGuard/discussions/categories/q-a
    about: Please create a discussion for questions or help requests.
